CREATE SCHEMA IF NOT EXISTS app;
CREATE USER {user} WITH PASSWORD '{password}';
REVOKE ALL ON DATABASE {db} FROM {user};
REVOKE ALL ON SCHEMA public FROM {user};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app TO {user};
