CREATE TABLE IF NOT EXISTS plan_service (
    plan_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL,
    CONSTRAINT fk_plan_id FOREIGN KEY (plan_id) REFERENCES plan(id)
        ON UPDATE CASCADE ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_service_id FOREIGN KEY (service_id) REFERENCES service(id)
        ON UPDATE CASCADE ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);
